stages:
  - build

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .m2/repository

build:jdk-8:
  stage: build
  image: maven:3.6.3-jdk-8
  script:
    - mvn clean package -DskipTests=false -pl !default-authorization-server-jdk17,!default-authorization-server-jdk17-1.2.0

build:jdk-17:
  stage: build
  image: maven:3.6.3-openjdk-17
  script:
    - mvn clean package -DskipTests=false
