# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java 17 CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-jdk-8

      - name: JDK Version
        run: java --version

      - name: Maven Version
        run: mvn --version

      - name: build JDK 17
        run: mvn clean package -DskipTests=false

      - name: build JDK 17 1.2.0
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.2.0

      - name: build JDK 17 1.1.4
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17 -Dspring-authorization-server.version=1.1.4

      - name: build JDK 17 1.1.3
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.1.3

      - name: build JDK 17 1.1.2
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.1.2

      - name: build JDK 17 1.1.1
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.1.1

      - name: build JDK 17 1.1.0
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.1.0

      - name: build JDK 17 1.0.4
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.0.4

      - name: build JDK 17 1.0.3
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.0.3

      - name: build JDK 17 1.0.2
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.0.2

      - name: build JDK 17 1.0.1
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.0.1

      - name: build JDK 17 1.0.0
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk17,default-authorization-server-jdk17-1.2.0 -Dspring-authorization-server.version=1.0.0

      - name: build JDK 17 0.3.0
        run: |
          echo "注意：org.springframework.security:spring-security-oauth2-authorization-server:0.3.0 是使用 JDK 11.0.15 构建的"
          echo "MANIFEST.MF 链接：https://s01.oss.sonatype.org/service/local/repositories/releases/archive/org/springframework/security/spring-security-oauth2-authorization-server/0.3.0/spring-security-oauth2-authorization-server-0.3.0.jar/!/META-INF/MANIFEST.MF"
          mvn clean package -DskipTests=false -pl default-authorization-server-jdk8-0.3.1 -Dspring-authorization-server.version=0.3.0
