# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java 8 CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-jdk-8

      - name: JDK Version
        run: java -version

      - name: Maven Version
        run: mvn --version

      - name: build JDK 8
        run: mvn clean package -DskipTests=false -pl !default-authorization-server-jdk17,!default-authorization-server-jdk17-1.2.0

      - name: build JDK 8 0.4.5
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8 -Dspring-authorization-server.version=0.4.5

      - name: build JDK 8 0.4.4
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8,default-authorization-server-jdk8-0.4.4 -Dspring-authorization-server.version=0.4.4

      - name: build JDK 8 0.4.3
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8,default-authorization-server-jdk8-0.4.4 -Dspring-authorization-server.version=0.4.3

      - name: build JDK 8 0.4.2
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8,default-authorization-server-jdk8-0.4.4 -Dspring-authorization-server.version=0.4.2

      - name: build JDK 8 0.4.1
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8,default-authorization-server-jdk8-0.4.4 -Dspring-authorization-server.version=0.4.1

      - name: build JDK 8 0.4.0
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8,default-authorization-server-jdk8-0.4.4 -Dspring-authorization-server.version=0.4.0

      - name: build JDK 8 0.3.1
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8-0.3.1 -Dspring-authorization-server.version=0.3.1

      - name: build JDK 8 0.2.3
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8-0.3.1 -Dspring-authorization-server.version=0.2.3

      - name: build JDK 8 0.2.2
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8-0.3.1 -Dspring-authorization-server.version=0.2.2

      - name: build JDK 8 0.2.1
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8-0.3.1 -Dspring-authorization-server.version=0.2.1

      - name: build JDK 8 0.2.0
        run: mvn clean package -DskipTests=false -pl default-authorization-server-jdk8-0.3.1 -Dspring-authorization-server.version=0.2.0
